server:
  port: 8082
token:
  secret: 'kajEgkbpCZKICOkuraCEB855q2WUc9AVqIkemL3V0Dm9Ezj4UajzJ3g18Hg7mCvY'
spring:
  application:
    name: asignacion-mongo
  data:
    mongodb:
      host: localhost
      #host: mongodb
      port: 27017
      database: asignacion
  cloud:
    function:
      definition: processor;processorDestination;publishingCostsAndRoutesFromEvent;processorResultCostsAndRoutes;processorUpdatePointOfSale;processorRemovePointOfSale;processorUpdateDestination;processorRemoveDestination
    stream:
      default-binder: kafka
      default:
        producer:
          useNativeEncoding: true
      bindings:
        event-costs-and-routes:
          destination: mongo-costs-and-routes-events
        processor-in-0:
          destination: redis-point-events
          group: redis-group
        processor-out-0:
          destination: mongo-result-point-events
        processorDestination-in-0:
          destination: redis-destination-events
        processorDestination-out-0:
          destination: mongo-result-destination-events
        processorResultCostsAndRoutes-in-0:
          destination: redis-costs-and-routes
          group: redis-costs-and-routes-group
        processorUpdatePointOfSale-in-0:
          destination: redis-update-point-events
          group: redis-update-point
        processorUpdatePointOfSale-out-0:
          destination: mongo-result-update-point
        processorRemovePointOfSale-in-0:
          destination: redis-remove-point-events
          group: redis-remove-point
        processorRemovePointOfSale-out-0:
          destination: mongo-result-remove-events
        processorUpdateDestination-in-0:
          destination: redis-update-destination-events
          group: redis-update-destination
        processorUpdateDestination-out-0:
          destination: mongo-result-update-events
        processorRemoveDestination-in-0:
          destination: redis-remove-destination-events
          group: redis-remove-destination
        processorRemoveDestination-out-0:
          destination: mongo-result-remove-events
      kafka:
        binder:
          consumer-properties:
            "value.deserializer": org.springframework.kafka.support.serializer.JsonDeserializer
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
            "enable.auto.commit": false
            "spring.json.trusted.packages": "*"
          producer-properties:
            "value.serializer": org.springframework.kafka.support.serializer.JsonSerializer
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer
          broker: localhost:9092 