server:
  port: 8082
token:
  secret: 'kajEgkbpCZKICOkuraCEB855q2WUc9AVqIkemL3V0Dm9Ezj4UajzJ3g18Hg7mCvY'
spring:
  application:
    name: asignacion-mongo
	data:
      mongodb:
		host: localhost
		#host: mongodb
		port: 27017
		database: asignacion
  cloud:
    function:
      definition: processorDestination;processorPointOfSale
    stream:
      default:
        producer:
          useNativeEncoding: true
      bindings:
        processorDestination-in-0:
          destination: redis-destination-events
          group: redis-group
        processorDestination-out-0:
          destination: mongo-result-events
        processorPointOfSale-in-0:
          destination: redis-point-events
		  group: redis-group
        processorPointOfSale-out-0:
          destination: mongo-result-events
      kafka:
      binder:
        consumer-properties:
          "value.deserializer": org.springframework.kafka.support.serializer.JsonDeserializer
          "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
          "auto.offset.reset": "earliest"
          "spring.json.trusted.packages": "com.capo.asignacion_mongo.adapter.in.events.*"
        producer-properties:
          "value.serializer": org.springframework.kafka.support.serializer.JsonSerializer
          "key.serializer": org.apache.kafka.common.serialization.StringSerializer